### ISSUE TITLE
which python3 

### ISSUE THREAD

**Issue by Chertoganov** [cosmic-cortex/fastAPI-ML-quickstart#1]
I'm running this command on anaconda on Windows and getting an error, what I suppose to do?

which python3 
'which' is not recognized as an internal or external command,
operable program or batch file.

**Comment by cosmic-cortex** [comment]
If you are using Anaconda, then you should use its built-in environment manager: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
