### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by Chertoganov** [cosmic-cortex/fastAPI-ML-quickstart#2]
it is waiting so long time and I can't see anything in http://localhost:8000/

$ docker run -p 8000:8000 fastapi-ml-quickstart
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:334: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.1 when using version 0.23.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:334: UserWarning: Trying to unpickle estimator RandomForestRegressor from version 0.22.1 when using version 0.23.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

**Comment by cosmic-cortex** [comment]
This is actually not an error, this is what supposed to happen. The container runs uvicorn, which serves your application locally. It is ready to start handling requests according to the last line. To see what kind of requests you can post, visit http://localhost:8000/docs.
